# Generated by Django 4.2 on 2023-04-21 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email number'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^989[0-3,9]\\d{8}$', 'Enter a valid mobile number.')], verbose_name='mobile number'),
        ),
    ]
