# Generated by Django 4.2 on 2023-04-22 11:32

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
